version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - Ayaka
  - balatro
  - cuda
  - cupti
  - easyocr
  - frontmatter
  - ipykernel
  - matplotlib
  - Neko
  - numpy
  - nvcc
  - onnx
  - onnxruntime
  - onnxslim
  - opencv
  - paddleocr
  - paddlepaddle
  - pixi
  - polygraphy
  - pyautogui
  - pylint
  - pynput
  - pypi
  - pytesseract
  - pytest
  - pyyaml
  - rapidocr
  - Tesseract
  - timm
  - torchvision
  - tqdm
  - ultralytics
  - wand
ignoreWords: []
import: []
