version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - Ayaka
  - balatro
  - frontmatter
  - ipykernel
  - matplotlib
  - Neko
  - numpy
  - onnx
  - onnxruntime
  - onnxslim
  - opencv
  - pixi
  - pyautogui
  - pynput
  - pypi
  - tqdm
  - ultralytics
  - wand
ignoreWords: []
import: []
