# Simple ruff configuration synced with .editorconfig
line-length = 88
target-version = "py312"

[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[lint]
ignore = [
  "E402",
]
